<div class="entry-edit" style="position: relative;">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
    </div>
    <div class="fieldset">
            <div id="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
                   </a>
              <?php echo $this->getOrder()->shipping_code.'- $'.$this->getOrder()->shipping_amount; ?>
    </div>
<div style="display: none; position: absolute; background-color: rgb(153, 153, 153); opacity: 0.8; width: 300px; height: 62px; top: 0px; left: 0px;" id="shipping-method-overlay" class="overlay"><span>Shipping method selection is not applicable</span></div>

    </div>
</div>

