<?php $status = $this->getStatusOptions(); ?>
<?php $statusHistory = $this->getOrder()->getStatuses(); ?>
<?php $currentStatus = $this->getOrder()->getCurrentStatus(); ?>

<div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4>Comments History</h4>
            </div>
            <fieldset><div id="order_history_block">
        <div id="history_form" class="order-history-form">
        <div>Add Order Comments</div>
        <span class="field-row">
            <label class="normal" for="history_status">Status</label><br>
            <select name="history[status]" class="select" id="history_status">

                    <?php foreach ($status as $key => $value) {?>
                          <?php if($status[$currentStatus->getStatus()]<=$value && $status[$currentStatus->getStatus()]!=3 ): ?>
                            <option value="<?php echo $key; ?>" <?php if($currentStatus->getStatus()==$key){ echo 'selected' ; } ?> ><?php echo $key; ?></option>
                          <?php endif; ?>  
                    <?php } ?>        
                        </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment">Comment</label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;"  id="history_comment"></textarea>
        </span>
        <div class="f-left">
                            <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1"><label class="normal" for="history_notify"> Notify Customer by Email</label><br>
        </div>
        <div class="f-right">
            <button id="status_button" title="Submit Comment" type="button"  onclick="statusButton()" class="scalable save" style=""><span><span><span>Submit Comment</span></span></span></button>        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
        <ul class="note-list">
           <?php foreach ($statusHistory as $key => $status):?> 
            <li>
            <strong><?php echo $status->getCreatedAt(); ?></strong>
            <span class="separator">|</span><strong><?php echo $status->getStatus(); ?></strong><br><small>Customer<strong class="subdue">
                            <?php if($status->getIsCustomerNotified()){ echo 'Notified';}else{ echo 'Not Notified';} ?>                         </strong></small>
                            <br>           
                          <?php echo $status->getComment(); ?>                
            </li>
           <?php endforeach;?> 
           <!--  <li>
            <strong>May 31, 2021</strong>
            11:50:00 PM<span class="separator">|</span><strong>Pending</strong><br><small>Customer            <strong class="subdue">
                                Not Notified                            </strong></small>
                    </li> -->
        </ul>
    
</div>
</fieldset>
        </div>
    </div>


<script type="text/javascript">
    
    function statusButton() {

       var form = document.getElementById('order_Form');
       form.setAttribute('action','<?php echo $this->getUrl('*/*/saveStatus',['_current'=>true]); ?>');
       form.submit();
    }

</script>