<div class="box-right entry-edit">
        <div class="entry-edit-head"><h4>Order Totals</h4></div>
        <div class="order-totals"><table cellspacing="0" width="100%">
    <colgroup><col>
    <col width="1">
            </colgroup><tfoot>
                    <tr class="0">
            <td class="label">
                <strong>Grand Total</strong>
            </td>
            <td class="emph">
                <strong><span class="price">$<?php echo $this->getOrder()->getGrandTotal(); ?></span></strong>
            </td>
        </tr>
                            <tr class="1">
            <td class="label">
                <strong>Total Paid</strong>
            </td>
            <td class="emph">
                <strong><span class="price">$0.00</span></strong>
            </td>
        </tr>
                            <tr class="2">
            <td class="label">
                <strong>Total Refunded</strong>
            </td>
            <td class="emph">
                <strong><span class="price">$0.00</span></strong>
            </td>
        </tr>
                            <tr class="3">
            <td class="label">
                <strong>Total Due</strong>
            </td>
            <td class="emph">
                <strong><span class="price">$<?php echo $this->getOrder()->getGrandTotal(); ?></span></strong>
            </td>
        </tr>
                </tfoot>
    
            <tbody>
                    <tr class="0">
            <td class="label">
                                Subtotal                            </td>
                        <td>
                <span class="price">$<?php echo $this->getOrder()->getSubtotal(); ?></span>                        </td>
        </tr>
                            <tr class="1">
            <td class="label">
                                Shipping &amp; Handling                            </td>
                        <td>
                <span class="price">$<?php echo $this->getOrder()->shipping_amount; ?></span>                        </td>
        </tr>
                </tbody>
    </table>
</div>
    </div>