<?php $products = $this->getProducts(); ?>
<form action="<?php echo $this->getUrl('*/*/save'); ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="products">
        <div id="order-search" class="order-search-items">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <div style="float: right;">
                        <button title="Add Selected Product(s) to Order" type="submit" class="scalable add" ><span><span><span>Add Selected Product(s) to Order</span></span></span></button>
                    </div>
                    <h4 class="fieldset-legend head-catalog-product icon-head">Please Select Products to Add</h4>
                </div>
                <div class="fieldset">

                    <div id="sales_order_create_search_grid">
                        <table cellspacing="0" class="actions">
                            <tr>
                                <td class="pager">
                                    Page
                                    <img src="http://127.0.0.1/phpCode/magento/skin/adminhtml/default/default/images/pager_arrow_left_off.gif" alt="Go to Previous page" class="arrow" />

                                    <input type="text" name="page" value="1" class="input-text page" onkeypress="sales_order_create_search_gridJsObject.inputPage(event, '1')" />

                                    <img src="http://127.0.0.1/phpCode/magento/skin/adminhtml/default/default/images/pager_arrow_right_off.gif" alt="Go to Next page" class="arrow" />

                                    of 1 pages <span class="separator">|</span>
                                    View <select name="limit" onchange="sales_order_create_search_gridJsObject.loadByElement(this)">
                                        <option value="20" selected="selected">20</option>
                                        <option value="30">30</option>
                                        <option value="50">50</option>
                                        <option value="100">100</option>
                                        <option value="200">200</option>
                                    </select>
                                    per page<span class="separator">|</span>
                                    Total 2 records found <span id="sales_order_create_search_grid-total-count" class="no-display">2</span>
                                </td>
                                <!-- <td class="filter-actions a-right">
                                    <button id="id_7c0958533cc870fbf8301343f54c2e56" title="Reset Filter" type="button" class="scalable " onclick="sales_order_create_search_gridJsObject.resetFilter()"><span><span><span>Reset Filter</span></span></span></button><button id="id_dd89a36aef33b66065ef93203f4f1f96" title="Search" type="button" class="scalable task" onclick="sales_order_create_search_gridJsObject.doFilter()"><span><span><span>Search</span></span></span></button>
                                </td> -->
                            </tr>
                        </table>
                        <div class="grid">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="data" id="sales_order_create_search_grid_table">
                                    <col width="60" />
                                    <col />
                                    <col width="80" />
                                    <col width="100" />
                                    <col width="55" />
                                    <col width="1" />
                                    <thead style="background-color: rgb(111, 137, 146);">
                                        <th style="color:white;">ID</th>
                                        <th style="color:white;">Product Name</th>
                                        <th style="color:white;">SKU</th>
                                        <th style="color:white;">Price</th>
                                        <th style="color:white;">Select</th>
                                        <!-- <tr class="headings">
                                            <th><span class="nobr"><a href="#" name="entity_id" title="asc" class="sort-arrow-desc"><span class="sort-title">ID</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title">Product Name</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="sku" title="asc" class="not-sort"><span class="sort-title">SKU</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="price" title="asc" class="not-sort"><span class="sort-title">Price</span></a></span></th>
                                            <th class="a-center no-link"><span class="nobr">Select</span></th>
                                            <th class=" no-link last"><span class="nobr">Qty To Add</span></th>
                                        </tr> -->
                                        <!-- <tr class="filter">
                                            <th>
                                                <div class="field-100"><input type="text" name="entity_id" id="sales_order_create_search_grid_filter_entity_id" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="field-100"><input type="text" name="name" id="sales_order_create_search_grid_filter_name" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="field-100"><input type="text" name="sku" id="sales_order_create_search_grid_filter_sku" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="range">
                                                    <div class="range-line"><span class="label">From:</span> <input type="text" name="price[from]" id="sales_order_create_search_grid_filter_price_from" value="" class="input-text no-changes" /></div>
                                                    <div class="range-line"><span class="label">To : </span><input type="text" name="price[to]" id="sales_order_create_search_grid_filter_price_to" value="" class="input-text no-changes" /></div>
                                                </div>
                                            </th>
                                            <th class="a-center no-link"><span class="head-massaction"><select name="in_products" id="sales_order_create_search_grid_filter_in_products" class="no-changes">
                                                        <option value="">Any</option>
                                                        <option value="1">Yes</option>
                                                        <option value="0">No</option>
                                                    </select></span></th>
                                            <th class=" no-link last">&nbsp;</th>
                                        </tr> -->
                                    </thead>

                                    <tbody>
                                        <?php foreach ($products as $key => $product) : ?>
                                            <tr title="#">
                                                <td class=" "><?php echo $product['entity_id']; ?></td>
                                                <td class=" "><?php echo $product['name']; ?></td>
                                                <td class=" "><?php echo $product['sku']; ?></td>
                                                <td class="a-center price a-right "><?php echo $product['price']; ?></td>
                                                <td class="a-center ">
                                                    <input type="checkbox" name="" value="<?php echo $product['entity_id']; ?>" class="checkbox" />
                                                </td>
                                                <!-- <td class="a-center last">
                                                    <input type="text" name="qty" value="" class="input-text qty" />
                                                </td> -->
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>