<h3 class="icon-head head-adminhtml-vendor-attribute"><?php echo $this->getHeaderText(); ?></h3>
<button style="float: right;" id="id_573a6279578cd8e9bae8cd6590bee179" title="Back" type="button" class="scalable back" onclick="window.location.href = '<?php echo $this->getUrl('*/adminhtml_order/'); ?>'" style=""><span><span><span>Back</span></span></span></button><br>
<hr><br>
<form method='post' action="<?php echo $this->getUrl('*/*/save',['_current'=>true]); ?>" >  
  <?php echo $this->getBlockHtml('formkey'); ?>
  <table style="width: 100%" cellspacing="2">
    <tbody>
      <tr>
        <td>
               <br><br>
        </td>
      </tr>
      <tr>
        <td colspan="2" style="padding: 10px">
          <?php echo $this->getChild('info')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>

      <tr>
        <td style="padding: 10px" colspan="2">
          <?php echo $this->getChild('order_item')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>

       <tr>
        <td style="padding: 10px">
          <?php echo $this->getChild('billing')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
        <td style="padding: 10px">
          <?php echo $this->getChild('shipping')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>

      <tr>
        <td style="padding: 10px">
          <?php echo $this->getChild('payment')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
        <td style="padding: 10px">
          <?php echo $this->getChild('shippment')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>

      <tr>
        <td></td>
        <td style="padding: 10px">
          <?php echo $this->getChild('total')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>
     </tbody> 
  </table>  

</form>


<script type="text/javascript">
  
</script>